import type { Identification, Listing, SearchInput } from '@/lib/schemas';
const photos={headphones:'photo-1546435770-a3e426bf472b',airpods:'photo-1625245488600-fbd7e4c1d2ef',chair:'photo-1592789705501-f9ae4278a2c9',camera:'photo-1516035069371-29a1b244cc32',bike:'photo-1485965120184-e220f721d03e'};
export const photo=(id:string)=>id===photos.chair?'/chair.jpg':id===photos.camera?'/camera.jpg':id===photos.headphones||id===photos.airpods?'/headphones.jpg':`https://images.unsplash.com/${id}?auto=format&fit=crop&w=700&q=85`;
export function demoIdentify(query:string):Identification {
 const q=query.toLowerCase();const productName=/airpod/.test(q)?'Apple AirPods Max':/aeron|chair|miller/.test(q)?'Herman Miller Aeron':/camera|fuji|sony a/.test(q)?'Fujifilm X100V':/bike|bicycle/.test(q)?'Trek FX 3':/sony|headphone|xm5/.test(q)||!q?'Sony WH-1000XM5':query.replace(/^(find me|find|search for)\s+/i,'').replace(/under\s*\$?\d+|near me/ig,'').trim();
 return {productName,brand:productName.split(' ')[0],model:productName.split(' ').slice(1).join(' '),category:/chair|aeron/i.test(productName)?'Office chair':/fuji/i.test(productName)?'Camera':'Electronics',color:'Black',attributes:['Secondhand','Demo identification — not an analysis of your photo'],confidence:.76,searchQueries:[productName,`${productName} used`]};
}
export function demoListings(id:string,input:SearchInput,identification:Identification):Listing[]{
 const name=identification.productName;const key=/AirPods/.test(name)?'airpods':/Aeron/.test(name)?'chair':/Fuji/.test(name)?'camera':/Trek/.test(name)?'bike':'headphones';
 const base=key==='chair'?420:key==='camera'?1150:key==='bike'?340:key==='airpods'?245:185;
 const specs=[{marketplace:'facebook',price:base,condition:'Like new',seller:'Alex M.',location:'Mission District · 2 mi',suffix:'— barely used',shipping:0},{marketplace:'ebay',price:base+24,condition:'Like new',seller:'soundgood_store',location:'Ships from California',suffix:'with original box',shipping:0},{marketplace:'facebook',price:base+40,condition:'Good',seller:'Sarah L.',location:'Oakland · 8 mi',suffix:'— excellent condition',shipping:0},{marketplace:'ebay',price:base+4,condition:'Good',seller:'secondlife_tech',location:'Ships from Oregon',suffix:'— tested & working',shipping:12.99},{marketplace:'facebook',price:base-20,condition:'Fair',seller:'Jordan K.',location:'Sunset District · 5 mi',suffix:'— light signs of wear',shipping:0},{marketplace:'ebay',price:base+64,condition:'Like new',seller:'renewed_collective',location:'Ships from New York',suffix:'— complete set',shipping:8.5},{marketplace:'facebook',price:base+14,condition:'Good',seller:'Chris D.',location:'Berkeley · 11 mi',suffix:'with accessories',shipping:0},{marketplace:'ebay',price:base+80,condition:'Like new',seller:'everyday_finds',location:'Ships from Washington',suffix:'— open box',shipping:0},{marketplace:'kijiji',price:base+30,condition:'Good',seller:'Morgan T.',location:'Toronto, ON · 6 mi',suffix:'— ready to go',shipping:0},{marketplace:'kijiji',price:base-10,condition:'Like new',seller:'Priya S.',location:'Vancouver, BC · 3 mi',suffix:'— rarely used',shipping:0}] as const;
 return specs.map((s,i)=>({id:`demo-${id}-${i}`,searchId:id,marketplace:s.marketplace,title:`${name} ${s.suffix}`,description:`Demo listing. ${name} in ${s.condition.toLowerCase()} condition. Includes the original accessories. All functions tested. ${s.marketplace==='ebay'?'Carefully packed and shipped within two business days.':'Local pickup available; arrange a time with the seller.'}`,price:s.price,currency:'USD' as const,shippingCost:s.shipping,imageUrls:[photo(photos[key])],listingUrl:s.marketplace==='facebook'?`https://www.facebook.com/marketplace/`:s.marketplace==='ebay'?`https://www.ebay.com/sch/i.html?_nkw=${encodeURIComponent(name)}`:`https://www.kijiji.ca/b-search.html?keywords=${encodeURIComponent(name)}`,condition:s.condition,sellerName:s.seller,sellerRating:[4.9,4.9,4.8,4.7,4.6,5,4.8,4.9,4.9,4.7][i],sellerReviewCount:[23,1240,18,392,8,2400,41,871,34,15][i],location:s.location,scrapedAt:Date.now(),confidence:.96,similarityScore:.98,demo:true}));
}
