'use client';
import { useState } from 'react';
import { Check, CheckCheck, Loader2, Send, ShieldCheck, Sparkles } from 'lucide-react';
import type { RankedListing } from '@/lib/schemas';
import { readStream } from '@/lib/client-stream';
import { money, MarketplaceBadge } from './listings';
import { Button } from './ui/button';
import { BrowserView } from './agent-panel';
export function NegotiationPanel({listing}:{listing:RankedListing}){const [desired,setDesired]=useState(Math.round(listing.price*.85));const [max,setMax]=useState(listing.price);const [tone,setTone]=useState('Friendly');const [message,setMessage]=useState('');const [token,setToken]=useState('');const [status,setStatus]=useState<'idle'|'drafting'|'draft'|'sending'|'sent'>('idle');const [error,setError]=useState('');const [url,setUrl]=useState('');
async function draft(){setError('');setToken('');setMessage('');setStatus('drafting');try{if(desired>max)throw new Error('Your opening offer must be at or below your maximum.');let result='';await readStream<{text?:string;token?:string;error?:string}>(await fetch('/api/negotiate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({listing,desiredPrice:desired,maxPrice:max,tone})}),e=>{if(e.error)throw new Error(e.error);if(e.text){result+=e.text;setMessage(result);}if(e.token)setToken(e.token);});setStatus('draft');}catch(e){setError((e as Error).message);setStatus('idle');}}
async function send(){setError('');setStatus('sending');let sent=false;try{await readStream<{status?:string;error?:string;debugUrl?:string}>(await fetch('/api/negotiate/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,message,approved:true})}),e=>{if(e.error)throw new Error(e.error);if(e.debugUrl)setUrl(e.debugUrl);if(e.status==='sent')sent=true;});if(!sent)throw new Error('Delivery not confirmed. Check the seller conversation before retrying.');setStatus('sent');}catch(e){setError((e as Error).message);setStatus('draft');}}
return <div className="negotiation"><div className="negotiation-listing"><img src={listing.imageUrls[0]||'/product.svg'} alt=""/><div><MarketplaceBadge marketplace={listing.marketplace}/><h4>{listing.title}</h4><strong>{money(listing.price)} <span>asking price</span></strong></div></div>{status==='sent'?<div className="send-success"><div><CheckCheck size={28}/></div><h3>{listing.demo?'Demo offer approved':'Your offer is on its way'}</h3><p>{listing.demo?'The approval workflow is complete. No real seller was contacted.':'The marketplace confirmed your message was sent.'}</p><blockquote>{message}</blockquote></div>:<><div className="offer-fields"><label>Your opening offer<div className="money-input"><span>$</span><input aria-label="Your opening offer" type="number" min="1" max={max} value={desired} disabled={status!=='idle'} onChange={e=>setDesired(Number(e.target.value))}/></div></label><label>Your walk-away price<div className="money-input"><span>$</span><input aria-label="Your walk-away price" type="number" min={desired} value={max} disabled={status!=='idle'} onChange={e=>setMax(Number(e.target.value))}/></div></label></div><p className="field-hint">Your maximum stays private. Scout only proposes your opening offer.</p><label className="field-label">Set the tone</label><div className="tone-options">{['Friendly','Direct','Flexible'].map(t=><button disabled={status!=='idle'} className={tone===t?'selected':''} key={t} onClick={()=>setTone(t)}>{tone===t&&<Check size={12}/>} {t}</button>)}</div>{status==='idle'?<Button className="full-width" onClick={draft}><Sparkles size={16}/>Draft an offer</Button>:<div className="draft-box"><div><span><Sparkles size={14}/>Your proposed message</span><small>{status==='drafting'?'Writing…':'Editable · not sent'}</small></div><textarea aria-label="Proposed message" value={message} maxLength={2000} onChange={e=>setMessage(e.target.value)} disabled={status==='drafting'||status==='sending'}/><div className="approval-note"><ShieldCheck size={15}/>Review and edit before you approve.</div><Button className="full-width" disabled={!token||message.trim().length<5||status==='sending'||status==='drafting'} onClick={send}>{status==='sending'?<Loader2 size={16} className="spin"/>:<Send size={15}/>} {status==='sending'?'Opening chat & sending…':'Approve & Send'}</Button>{status==='draft'&&<button className="text-button" onClick={()=>{setStatus('idle');setMessage('');setToken('');}}>Change offer strategy</button>}</div>}</>}{error&&<div className="error-state" role="alert">{error}</div>}{url&&status==='sending'&&<BrowserView url={url}/>}<p className="negotiation-footer"><ShieldCheck size={13}/>{listing.demo?'Demo mode · no real messages are sent':'Only the exact message you approve will be sent'}</p></div>;}
