'use client';
import { useEffect, useState } from 'react';
import { useMutation, useQuery } from 'convex/react';
import { api } from '@/convex/_generated/api';
import type { Doc } from '@/convex/_generated/dataModel';
import { negotiationSettings, type NegotiationSettings } from '@/lib/negotiation/contracts';
import type { Listing } from '@/lib/schemas';
import { readJsonResponse } from '@/lib/client-stream';
import { Button } from './ui/button';
import { Modal } from './ui/dialog';
import { money } from './listings';
import { BrowserView } from './agent-panel';

type DemoThread={key:string;listing:Listing;settings:NegotiationSettings;status:string;step:number;messages:{role:string;text:string}[];lastCheckedAt?:number};
const demoKey=(id:string)=>`hf:threads:${id}`;
function readDemo(id:string):DemoThread[]{try{return JSON.parse(sessionStorage.getItem(demoKey(id))||'[]');}catch{return [];}}
function writeDemo(id:string,rows:DemoThread[]){sessionStorage.setItem(demoKey(id),JSON.stringify(rows));window.dispatchEvent(new Event('hf:conversations'));}
async function operation(body:unknown){return readJsonResponse(await fetch('/api/workspace/negotiations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));}

// Shared by the manual "Set up negotiation" form and the top-deals Like button, so both start
// (or edit) a negotiation identically instead of duplicating the demo-vs-live branching.
export async function startNegotiationFor(listing:Listing,settings:NegotiationSettings,existing?:{key:string;version:number}){
 if(listing.demo){const rows=readDemo(listing.searchId);if(rows.some(t=>t.listing.id===listing.id&&!['stopped','expired'].includes(t.status)))throw new Error('A demo negotiation already exists. View it in Negotiations.');rows.push({key:crypto.randomUUID(),listing,settings,status:'active',step:0,messages:[{role:'outgoing',text:`Demo opening offer: ${money(settings.openingOffer,listing.currency)} for the item.`}]});writeDemo(listing.searchId,rows);return;}
 await operation(existing?{action:'edit',key:existing.key,version:existing.version,settings,authorized:true}:{action:'start',workspaceId:listing.searchId,listingId:listing.id,settings,authorized:true});
}

export function NegotiationSetup({listing,existing,onStarted}:{listing:Listing;existing?:Doc<'threads'>;onStarted:()=>void}){
 const [openingOffer,setOpening]=useState(existing?.settings.openingOffer??Math.round(listing.price*.8));const [maximum,setMaximum]=useState(existing?.settings.maximum??Math.round(listing.price*.95));const [tone,setTone]=useState(existing?.settings.tone??'Friendly');const [basis,setBasis]=useState(existing?.settings.costBasis??'pickup');const [instructions,setInstructions]=useState(existing?.settings.instructions??'');const [hours,setHours]=useState(24);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function start(){setBusy(true);setError('');try{const settings=negotiationSettings.parse({openingOffer,maximum,currency:listing.currency,costBasis:basis,tone,instructions,expiresAt:Date.now()+hours*3600_000});
  await startNegotiationFor(listing,settings,existing);onStarted();
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div><h3>{listing.title}</h3><p>{listing.demo?'Simulated negotiation. No seller is contacted.':'Start authorizes an ongoing seller conversation under these limits. Your maximum stays private.'}</p><div className="negotiation-fields"><label>Opening offer ({listing.currency})<input type="number" min="1" step="0.01" value={openingOffer} onChange={e=>setOpening(Number(e.target.value))}/></label><label>Hard maximum ({listing.currency})<input type="number" min="1" step="0.01" value={maximum} onChange={e=>setMaximum(Number(e.target.value))}/></label><label>Cost basis<select value={basis} onChange={e=>setBasis(e.target.value as typeof basis)}><option value="pickup">Item price · pickup</option><option value="shipped">Item plus shipping</option></select></label><label>Tone<select value={tone} onChange={e=>setTone(e.target.value as typeof tone)}><option>Friendly</option><option>Direct</option><option>Flexible</option></select></label><label>Authorization duration<select value={hours} onChange={e=>setHours(Number(e.target.value))}><option value={1}>1 hour</option><option value={6}>6 hours</option><option value={24}>24 hours</option></select></label><label className="full">Additional instructions<textarea rows={3} maxLength={2000} value={instructions} onChange={e=>setInstructions(e.target.value)}/></label></div><p className="field-hint">You can pause or stop at any time. The first acceptable deal pauses competing negotiations. Payment, logistics, formal offers, bids, and purchases are excluded.</p>{error&&<p role="alert" className="error-state">{error}</p>}<Button disabled={busy||openingOffer<=0||maximum<openingOffer} onClick={()=>void start()}>{busy?'Saving authorization…':existing?'Save new authorization':'Start negotiation'}</Button></div>;
}
function LiveConversation({thread,listings}:{thread:Doc<'threads'>;listings:Listing[]}){
 const schedule=useQuery(api.conversations.schedule,{key:thread.key});
 const data=useQuery(api.conversations.messages,{key:thread.key});const [editing,setEditing]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const listing=listings.find(l=>l.id===thread.listingId);
 async function act(action:string){setBusy(true);setError('');try{await operation({action,key:thread.key,version:thread.version});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <article className="conversation-card"><h3>{listing?.title||'Seller conversation'}</h3><p><strong>{thread.status==='agreed'?'Price agreed':thread.status.replaceAll('_',' ')}</strong>{thread.currentOffer!==undefined?` · ${money(thread.currentOffer,thread.settings.currency)}`:''}</p>{thread.reason&&<p>{thread.reason}</p>}<p className="field-hint">{thread.lastCheckedAt?`Last checked ${new Date(thread.lastCheckedAt).toLocaleTimeString()}`:'First check pending'} · {schedule?.nextDueAt&&thread.status==='active'?`Next check ${new Date(schedule.nextDueAt).toLocaleTimeString()}`:'Monitoring paused or inactive'} · expires {new Date(thread.settings.expiresAt).toLocaleString()}</p>{schedule?.debugUrl&&<details><summary>Live browser</summary><BrowserView url={schedule.debugUrl}/></details>}<div className="conversation-messages">{data?.messages.map(m=><div key={m._id} className={`conversation-message ${m.role}`}><small>{m.role==='incoming'?'Seller':'You / agent'}</small><p>{m.text}</p></div>)}{data?.attempts.filter(a=>!a.sourceId).map(a=><div key={a._id} className="conversation-message outgoing"><small>Agent · {a.status}</small><p>{a.text}</p></div>)}{data===undefined&&<p role="status">Loading conversation…</p>}</div><div className="conversation-controls"><Button disabled={busy||thread.status==='stopped'||thread.status==='agreed'} variant="outline" onClick={()=>void act('check')}>Check now</Button><Button disabled={busy||['stopped','agreed','uncertain'].includes(thread.status)} variant="outline" onClick={()=>void act(thread.status==='active'?'pause':'resume')}>{thread.status==='active'?'Pause':'Resume'}</Button><Button disabled={busy||['stopped','agreed'].includes(thread.status)} variant="outline" onClick={()=>setEditing(true)}>Edit limits / Extend expiry</Button><Button disabled={busy||['stopped','agreed'].includes(thread.status)} variant="ghost" onClick={()=>void act('stop')}>Stop negotiation</Button><a href={thread.listingUrl} target="_blank" rel="noreferrer">Open marketplace</a></div>{error&&<p role="alert">{error}</p>}<Modal open={editing} onOpenChange={setEditing} title="Update negotiation authorization">{listing&&<NegotiationSetup listing={listing} existing={thread} onStarted={()=>setEditing(false)}/>}</Modal></article>;
}
function LiveNegotiations({workspaceId,listings}:{workspaceId:string;listings:Listing[]}){
 const threads=useQuery(api.conversations.list,{workspaceId});const workspace=useQuery(api.store.workspace,{id:workspaceId});const pause=useMutation(api.store.setMonitoringPaused);const [error,setError]=useState('');
 return <><Button variant="outline" onClick={()=>void pause({id:workspaceId,paused:!workspace?.summary.monitoringPaused}).catch(()=>setError('Could not change monitoring. Try again.'))}>{workspace?.summary.monitoringPaused?'Resume monitoring':'Pause monitoring'}</Button>{error&&<p role="alert">{error}</p>}{threads===undefined?<p role="status">Loading negotiations…</p>:threads.length?<div className="conversation-list">{threads.map(t=><LiveConversation key={t.key} thread={t} listings={listings}/>)}</div>:<p>No negotiations yet. Open a product and choose Set up negotiation.</p>}</>;
}
function advanceDemo(workspaceId:string,key:string,action:string,paused:boolean){const next=readDemo(workspaceId);const row=next.find(t=>t.key===key)!;if(action==='stop')row.status='stopped';else if(action==='pause')row.status='paused';else if(action==='resume')row.status='active';else if(action==='extend'){row.settings.expiresAt=Date.now()+86400_000;if(row.status==='expired')row.status='active';}else if(!paused&&row.status==='active'){
  if(row.settings.expiresAt<=Date.now())row.status='expired';else{row.step++;row.lastCheckedAt=Date.now();const amount=Math.min(row.settings.maximum,Math.round(row.settings.openingOffer*1.1));
   if(row.step===1)row.messages.push({role:'incoming',text:`Demo seller: could you do ${money(amount,row.settings.currency)}?`},{role:'outgoing',text:`Demo counteroffer: would ${money(amount,row.settings.currency)} work?`});
   else if(row.step===2)row.messages.push({role:'incoming',text:'Demo seller: are you still interested?'},{role:'outgoing',text:'Yes, I am still interested. Thank you!'});
   else{row.messages.push({role:'incoming',text:`Demo seller: ${money(amount,row.settings.currency)} works.`},{role:'outgoing',text:`Demo price agreed: ${money(amount,row.settings.currency)}. Handle next steps personally.`});row.status='agreed';for(const other of next)if(other.key!==key&&other.status==='active')other.status='paused';}
  }}writeDemo(workspaceId,next);}
function DemoNegotiations({workspaceId}:{workspaceId:string}){
 const [rows,setRows]=useState<DemoThread[]>([]);const [paused,setPaused]=useState(false);
 useEffect(()=>{const load=()=>{setRows(readDemo(workspaceId));setPaused(sessionStorage.getItem(`hf:pause:${workspaceId}`)==='true');};queueMicrotask(load);window.addEventListener('hf:conversations',load);return()=>window.removeEventListener('hf:conversations',load);},[workspaceId]);
 const act=(key:string,action:string)=>advanceDemo(workspaceId,key,action,paused);
 return <><p className="demo-results-note">Simulated conversations. Check now advances the controlled demo; no real seller or background browser is involved.</p><Button variant="outline" onClick={()=>{sessionStorage.setItem(`hf:pause:${workspaceId}`,String(!paused));setPaused(!paused);}}>{paused?'Resume monitoring':'Pause monitoring'}</Button>{rows.length?<div className="conversation-list">{rows.map(row=><article className="conversation-card" key={row.key}><h3>{row.listing.title}</h3><strong>{row.status==='agreed'?'Price agreed':row.status}</strong><div className="conversation-messages">{row.messages.map((m,i)=><div className={`conversation-message ${m.role}`} key={i}>{m.text}</div>)}</div><div className="conversation-controls"><Button disabled={paused||row.status!=='active'} onClick={()=>act(row.key,'check')}>Check now</Button><Button variant="outline" disabled={['stopped','agreed'].includes(row.status)} onClick={()=>act(row.key,row.status==='active'?'pause':'resume')}>{row.status==='active'?'Pause':'Resume'}</Button><Button variant="outline" onClick={()=>act(row.key,'extend')}>Extend expiry</Button><Button variant="ghost" onClick={()=>act(row.key,'stop')}>Stop negotiation</Button></div></article>)}</div>:<p>No negotiations yet. Choose a product to get started.</p>}</>;
}
export function WorkspaceNegotiations({workspaceId,listings,demo}:{workspaceId:string;listings:Listing[];demo:boolean}){return <section className="workspace-page"><h2>Negotiations</h2>{demo?<DemoNegotiations workspaceId={workspaceId}/>:<LiveNegotiations workspaceId={workspaceId} listings={listings}/>}</section>;}
function LiveObserver({id,onIds}:{id:string;onIds:(ids:string[])=>void}){const rows=useQuery(api.conversations.list,{workspaceId:id});useEffect(()=>{if(rows)onIds(rows.map(row=>row.listingId));},[rows,onIds]);return null;}
export function NegotiationObserver({id,demo,onIds}:{id:string;demo:boolean;onIds:(ids:string[])=>void}){useEffect(()=>{if(!demo)return;const load=()=>onIds(readDemo(id).map(row=>row.listing.id));queueMicrotask(load);window.addEventListener('hf:conversations',load);return()=>window.removeEventListener('hf:conversations',load);},[id,demo,onIds]);return demo?null:<LiveObserver id={id} onIds={onIds}/>;}
