import { approvalSchema } from '@/lib/schemas';
import { verifyOffer } from '@/lib/server/approval';
import { apiError, connection, saveNegotiation, userId } from '@/lib/server/context';
import { createSession,connectBrowser,releaseSession,viewerUrl } from '@/lib/steel/sessions';
import { sendSellerMessage as facebookSend } from '@/lib/marketplaces/facebook/messaging';
import { sendSellerMessage as ebaySend } from '@/lib/marketplaces/ebay/messaging';
import { sendSellerMessage as kijijiSend } from '@/lib/marketplaces/kijiji/messaging';
const senders={facebook:facebookSend,ebay:ebaySend,kijiji:kijijiSend} as const;
export const maxDuration=120;
export async function POST(req:Request){try{const user=await userId();const input=approvalSchema.parse(await req.json());const offer=verifyOffer(input.token,user);if(offer.listing.demo)return Response.json({status:'sent',demo:true,message:'Demo message approved. No real seller was contacted.'});await saveNegotiation(user,offer.id,{...offer,status:'sending',approvedMessage:input.message,approvedAt:Date.now()},true);const encoder=new TextEncoder();return new Response(new ReadableStream({async start(c){const emit=(v:unknown)=>c.enqueue(encoder.encode(JSON.stringify(v)+'\n'));let sessionId:string|undefined;try{const profile=await connection(user,offer.listing.marketplace);if(!profile)throw new Error('Connect your marketplace account before sending.');const session=await createSession(profile.profileId);sessionId=session.id;emit({debugUrl:viewerUrl(session.debugUrl),message:'Opening seller conversation'});const {browser,page}=await connectBrowser(session.id);try{await senders[offer.listing.marketplace](page,offer.listing,input.message);}finally{await browser.close().catch(()=>{});}await saveNegotiation(user,offer.id,{...offer,status:'sent',approvedMessage:input.message,sentAt:Date.now()});emit({status:'sent',message:'Message sent and confirmed.'});}catch(e){await saveNegotiation(user,offer.id,{...offer,status:'unconfirmed',approvedMessage:input.message}).catch(()=>{});emit({error:e instanceof Error?e.message:'Sending could not be confirmed. Check the conversation before trying again.'});}finally{if(sessionId)await releaseSession(sessionId).catch(()=>{});c.close();}}}),{headers:{'Content-Type':'application/x-ndjson','Cache-Control':'no-store'}});}catch(e){return apiError(e);}}
